module.exports = {
    products: [
        { key: "1", name: "insaatdemiri"},
        { key: "2", name: "celikhasir"},
        { key: "3", name: "filmasin"},
        { key: "4", name: "inp"} ,
        { key: "5", name: "hea"} ,
        { key: "6", name: "kosebent"},
        { key: "7", name: "lama"} ,
        { key: "8", name: "karedd"},
        { key: "9", name: "dyd"} ,
        { key: "10", name: "t-demiri"} ,
        { key: "11", name: "transmisyon"} ,
        { key: "12", name: "shr"},
        { key: "14", name: "dkp"} ,
        { key: "15", name: "hrp"} ,
        { key: "16", name: "gr"} ,
        { key: "17", name: "bs"} ,
        { key: "18", name: "bgds"},
        { key: "19", name: "tos"},
        { key: "20", name: "gds"} ,
        { key: "21", name: "kdkp"},
        { key: "22", name: "gkpb"},
        { key: "23", name: "sb"} ,
        { key: "24", name: "sgb"},
        { key: "25", name: "ssb"},
        { key: "26", name: "ccb"} ,
        { key: "27", name: "filmasin"},
    ]
  };