module.exports = {
    products: {
        'insaatdemiri': { },
        'celikhasir': { },
        'filmasin': { },
        'inp': { } ,
        'hea': { } ,
        'kosebent': { },
        'lama': { } ,
        'karedd': { },
        'dyd': { } ,
        't-demiri': { } ,
        'transmisyon': { } ,
        'shr': { },
        'shl': { } ,
        'dkp': { } ,
        'hrp': { } ,
        'gr': { } ,
        'bs': { } ,
        'bgds': { },
        'tos': { },
        'gds': { } ,
        'kdkp': { },
        'gkpb': { },
        'sb': { } ,
        'sgb': { },
        'ssb': { },
        'ccb': { } ,
        'filmasin': { },
    }
  };